Repository prgrms-web-devcourse-final-project/WEB5_7_F1_BE, pull requests merged in 2025-07, with the labels that each got.

#8 :sparkles: feat: GitHub Action 자동 Release 추가
  .github/workflows/release.yml
Labels: enhancement

#10 [feat] GitHub Action 자동 테스트 추가
  .github/workflows/test.yml
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/user/entity/User.java
  backend/src/test/resources/application.yml
Labels: enhancement

#17 [feat] 퀴즈 생성 기능 추가
  backend/.gitignore
  backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java
  backend/src/main/java/io/f1/backend/domain/question/dao/QuestionRepository.java
  backend/src/main/java/io/f1/backend/domain/question/dao/TextQuestionRepository.java
  backend/src/main/java/io/f1/backend/domain/question/dto/QuestionRequest.java
  backend/src/main/java/io/f1/backend/domain/question/entity/Question.java
  backend/src/main/java/io/f1/backend/domain/question/entity/TextQuestion.java
  backend/src/main/java/io/f1/backend/domain/question/mapper/QuestionMapper.java
  backend/src/main/java/io/f1/backend/domain/question/mapper/TextQuestionMapper.java
  backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/dao/QuizRepository.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateRequest.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateResponse.java
  backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java
  backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java
  backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/io/f1/backend/global/config/WebConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/resources/application.yml
Labels: enhancement

#19 [feat] 방 입장 및 validation 체크
  backend/.gitignore
  backend/src/main/java/io/f1/backend/domain/game/api/RoomController.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomInitialData.java
  backend/src/main/java/io/f1/backend/domain/game/dto/WebSocketDto.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoomCreateRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoomValidationRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/DefaultWebSocketResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/GameSettingResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/PlayerListResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/PlayerResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/QuizResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/RoomSettingResponse.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepository.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepositoryImpl.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java
  backend/src/main/java/io/f1/backend/global/config/StompChannelInterceptor.java
  backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java
Labels: enhancement

#24 [feat] Kakao OAuth 회원가입, 로그인, 로그아웃 기능
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/stat/entity/Stat.java
  backend/src/main/java/io/f1/backend/domain/user/api/SignupController.java
  backend/src/main/java/io/f1/backend/domain/user/app/CustomOAuthUserService.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/CustomAuthenticationEntryPoint.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/OAuthLogoutSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/OAuthSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/io/f1/backend/domain/user/dto/SessionUser.java
  backend/src/main/java/io/f1/backend/domain/user/dto/SignupRequestDto.java
  backend/src/main/java/io/f1/backend/domain/user/dto/SignupResponseDto.java
  backend/src/main/java/io/f1/backend/domain/user/dto/UserPrincipal.java
  backend/src/main/java/io/f1/backend/domain/user/entity/User.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
  backend/src/main/resources/application.yml
Labels: enhancement

#27 fix: 테스트 시 security 설정이 되어 있지 않아 발생하는 오류 수정
  .github/workflows/test.yml
  backend/src/test/resources/application.yml
Labels: bug

#30 [feat] Github Action 자동 도커 이미지 빌드 추가
  .github/workflows/bump-version.yml
  .github/workflows/release.yml
  backend/Dockerfile
  backend/src/main/resources/application.yml
Labels: enhancement

#29 [feat] SSE 알림 기능 구현
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/event/RoomCreatedEvent.java
  backend/src/main/java/io/f1/backend/domain/game/event/RoomDeletedEvent.java
  backend/src/main/java/io/f1/backend/domain/game/event/RoomUpdatedEvent.java
  backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java
  backend/src/main/java/io/f1/backend/domain/game/sse/dto/LobbySseEvent.java
  backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomCreatedPayload.java
  backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomDeletedPayload.java
  backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomUpdatedPayload.java
  backend/src/main/java/io/f1/backend/domain/game/sse/dto/SseEventType.java
  backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomCreatedEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomDeletedEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomUpdatedEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/sse/mapper/SseMapper.java
  backend/src/main/java/io/f1/backend/domain/game/sse/store/SseEmitterRepository.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
Labels: enhancement

#31 [feat] 퀴즈 조회, 수정, 삭제 API 구현
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/dao/QuizRepository.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizListPageResponse.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizListResponse.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizUpdateRequest.java
  backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java
  backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java
Labels: enhancement

#40 [feat] 사용자 회원탈퇴, 닉네임 수정
  backend/src/main/java/io/f1/backend/domain/user/api/UserController.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/java/io/f1/backend/global/config/WebConfig.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
Labels: enhancement

#41 [feat] 커스텀 예외 공통 처리
  backend/src/main/java/io/f1/backend/global/exception/CustomException.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/AuthErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/CommonErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/ErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/QuestionErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/QuizErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/UserErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/io/f1/backend/global/exception/response/ErrorResponse.java
Labels: enhancement

#44 [feat] 문제 수정, 삭제 API 구현
  backend/src/main/java/io/f1/backend/domain/question/api/QuestionController.java
  backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java
  backend/src/main/java/io/f1/backend/domain/question/dto/QuestionRequest.java
  backend/src/main/java/io/f1/backend/domain/question/dto/QuestionUpdateRequest.java
  backend/src/main/java/io/f1/backend/domain/question/entity/Question.java
  backend/src/main/java/io/f1/backend/domain/question/entity/TextQuestion.java
  backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateRequest.java
  backend/src/main/java/io/f1/backend/global/validation/TrimmedSize.java
  backend/src/main/java/io/f1/backend/global/validation/TrimmedSizeValidator.java
Labels: enhancement

#54 [refactor] 커스텀 예외 적용
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/global/config/StompChannelInterceptor.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
Labels: refactoring

#56 [refactor] Mapper에서 NPE 요소 제거하기 + 커스텀 예외 적용하기
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java
  backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java
  backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/GameErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/QuestionErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/QuizErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
  backend/src/main/resources/application.yml
Labels: refactoring

#57 [feat] 플레이어 준비 상태 변경 기능
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/PlayerReadyData.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepository.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepositoryImpl.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
Labels: enhancement

#59 [feat] : 대기중 채팅, 게임중 채팅(정답 판별) 구현
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/ChatMessage.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/Rank.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoundResult.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/DefaultWebSocketRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/QuestionResultResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/RankUpdateResponse.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/Player.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
Labels: enhancement

#62 [refactor] 커스텀 예외처리 적용
  backend/src/main/java/io/f1/backend/domain/admin/app/AdminDetailService.java
  backend/src/main/java/io/f1/backend/domain/admin/app/handler/AdminLoginFailureHandler.java
  backend/src/main/java/io/f1/backend/domain/admin/app/handler/AdminLoginSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/user/api/SignupController.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/CustomAuthenticationEntryPoint.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/OAuthSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/user/dto/SignupResponse.java
  backend/src/main/java/io/f1/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/AdminErrorCode.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
  backend/src/main/resources/application.yml
Labels: refactoring

#71 [fix] CORS 경로 설정, HTTPS 환경설정
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
  backend/src/main/resources/application.yml
Labels: bug

#81 feat: PR Open 시 Slack 알림 Github Action 추가
  .github/workflows/slack-notify-pr-open.yml
Labels: enhancement

#77 [feat] 관리자 퀴즈 수정, 삭제 로직 추가 + User 하드코딩 삭제
  backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
Labels: enhancement, refactoring

#82 [feat] 유저 목록 조회 기능
  backend/src/main/java/io/f1/backend/domain/admin/api/AdminController.java
  backend/src/main/java/io/f1/backend/domain/admin/app/AdminService.java
  backend/src/main/java/io/f1/backend/domain/admin/dto/UserPageResponse.java
  backend/src/main/java/io/f1/backend/domain/admin/dto/UserResponse.java
  backend/src/main/java/io/f1/backend/domain/admin/entity/Admin.java
  backend/src/main/java/io/f1/backend/domain/admin/mapper/AdminMapper.java
  backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/java/io/f1/backend/global/filter/DevTokenAuthFilter.java
  backend/src/main/resources/application.yml
  backend/src/test/java/io/f1/backend/domain/admin/app/AdminServiceTests.java
  backend/src/test/resources/datasets/admin/sorted-user.yml
Labels: enhancement

#88 [release] v0.0.4 RELEASE
  backend/src/main/java/io/f1/backend/domain/admin/api/AdminController.java
  backend/src/main/java/io/f1/backend/domain/admin/app/AdminService.java
  backend/src/main/java/io/f1/backend/domain/admin/dto/UserPageResponse.java
  backend/src/main/java/io/f1/backend/domain/admin/dto/UserResponse.java
  backend/src/main/java/io/f1/backend/domain/admin/entity/Admin.java
  backend/src/main/java/io/f1/backend/domain/admin/mapper/AdminMapper.java
  backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java
  backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/java/io/f1/backend/global/filter/DevTokenAuthFilter.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
  backend/src/main/resources/application.yml
  backend/src/test/java/io/f1/backend/domain/admin/app/AdminServiceTests.java
  backend/src/test/resources/datasets/admin/sorted-user.yml
Labels: bump:patch

#83 [refactor] 게임 시작 요청 리팩토링
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/GameStartRequest.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/GameErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
Labels: refactoring

#87 [refactor] convertAndSend 계층 변경
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomExitData.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomInitialData.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoundResult.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
Labels: refactoring

#93 [feat] 비밀방 여부 포함
  backend/src/main/java/io/f1/backend/domain/game/dto/response/RoomSettingResponse.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
Labels: enhancement

#94 [feat] 게임 시작 후 게임 진행 + 타이머 기능 추가
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/app/TimerService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/GameEventType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomEventType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/SystemNoticeMessage.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/QuestionResultResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/QuestionStartResponse.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/GameSetting.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/resources/data.sql
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
Labels: enhancement

#101 [feat] 유저 닉네임으로 정보 조회
  backend/src/main/java/io/f1/backend/domain/admin/api/AdminController.java
  backend/src/main/java/io/f1/backend/domain/admin/app/AdminService.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java
  backend/src/test/java/io/f1/backend/domain/admin/app/AdminServiceTests.java
  backend/src/test/resources/datasets/admin/search-user.yml
Labels: enhancement

#102 [feat] 재연결 로직 구현
  backend/src/main/java/io/f1/backend/domain/auth/dto/CurrentUserAndAdminResponse.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomEventType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/SystemNoticeMessage.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/Player.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/service/SessionService.java
  backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
  backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/websocket/SessionServiceTests.java
  backend/src/test/resources/application.yml
Labels: enhancement

#114 [release] v0.0.6 RELEASE
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/GameSettingChanger.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoundChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/TimeLimit.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/TimeLimitChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/GameSetting.java
  backend/src/main/java/io/f1/backend/domain/game/model/Player.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomDeletedEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomUpdatedEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepository.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepositoryImpl.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/stat/api/StatController.java
  backend/src/main/java/io/f1/backend/domain/stat/app/StatService.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatJpaRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRedisRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepositoryAdapter.java
  backend/src/main/java/io/f1/backend/domain/stat/dto/StatWithNicknameAndUserId.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/dto/UserSummary.java
  backend/src/main/java/io/f1/backend/global/config/RedisConfig.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/GameErrorCode.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
  backend/src/main/java/io/f1/backend/global/util/RedisPublisher.java
  backend/src/main/java/io/f1/backend/global/util/RedisUserSubscriber.java
  backend/src/main/resources/application.yml
  backend/src/test/java/io/f1/backend/domain/stat/RedisStatBrowserTest.java
  backend/src/test/java/io/f1/backend/domain/stat/StatBrowserTest.java
  backend/src/test/java/io/f1/backend/global/config/RedisTestContainerConfig.java
Labels: bump:patch

#116 [fix] 라운드 변경 시 question 조회에 fetch join 적용
  backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoundChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/model/GameSetting.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/dao/QuizRepository.java
Labels: bug

#120 [feat] 프로메테우스 적용
  backend/build.gradle
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: enhancement

#112 [refactor] 개인 메세지 구현
  backend/src/main/java/io/f1/backend/domain/auth/dto/CurrentUserAndAdminResponse.java
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomEventType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/SystemNoticeMessage.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/ExitSuccessResponse.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/service/SessionService.java
Labels: refactoring

#122 [release] v0.0.7 RELEASE
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/auth/dto/CurrentUserAndAdminResponse.java
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/app/TimerService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/RoomEventType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/SystemNoticeMessage.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoundChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/ExitSuccessResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/GameResultListResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/GameResultResponse.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/QuestionStartResponse.java
  backend/src/main/java/io/f1/backend/domain/game/event/GameCorrectAnswerEvent.java
  backend/src/main/java/io/f1/backend/domain/game/event/GameTimeoutEvent.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/GameSetting.java
  backend/src/main/java/io/f1/backend/domain/game/model/Player.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/model/RoomState.java
  backend/src/main/java/io/f1/backend/domain/game/store/RoomRepositoryImpl.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/service/SessionService.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/quiz/dao/QuizRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatJpaRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRedisRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepositoryAdapter.java
  backend/src/main/java/io/f1/backend/domain/stat/dto/StatWithUserSummary.java
  backend/src/main/java/io/f1/backend/domain/user/api/UserController.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/dto/MyPageInfo.java
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/store/RoomRepositoryTests.java
  backend/src/test/java/io/f1/backend/domain/game/websocket/SessionServiceTests.java
  backend/src/test/java/io/f1/backend/domain/stat/RedisStatBrowserTest.java
Labels: bump:patch

#125 [fix] 게임 종료 시 PLAYER_LIST 메세지 누락, 방장 레디 풀림 이슈 해결
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
Labels: bug

#127 [refactor] SSE 방 삭제 이벤트 퍼블리싱, 유저 수 조회 메서드 변경
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/GameSettingChanger.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/RoundChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/dto/request/TimeLimitChangeRequest.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/sse/mapper/SseMapper.java
Labels: refactoring

#133 [docs] 운영 / 개발 환경 분리
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
  backend/src/main/resources/application.yml
Labels: documentation

#140 [docs] 개발 서버용 cors 추가
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
Labels: documentation

#141 [release] v0.0.9 RELEASE
  backend/src/main/java/io/f1/backend/global/config/CorsConfig.java
Labels: bump:patch

#147 [docs] Http Basic 적용
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
Labels: documentation

#154 [refactor] 프로메테우스 관련 Basic Auth 설정 해제
  backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: refactoring

#157 [refactor] SSE 세션 유지 30분으로 수정
  backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java
Labels: refactoring

#159 [refactor] 재연결 로직 리팩토링
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/event/GameCorrectAnswerEvent.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/store/UserRoomRepository.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/DisconnectTaskManager.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/service/SessionService.java
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/websocket/SessionServiceTests.java
Labels: refactoring

#164 [feat] SSE 하트비트 추가
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java
  backend/src/main/java/io/f1/backend/domain/game/sse/store/SseEmitterRepository.java
Labels: enhancement

#167 [release] v0.0.13 RELEASE
  .github/workflows/test.yml
  backend/build.gradle
  backend/src/main/java/io/f1/backend/domain/admin/app/AdminDetailService.java
  backend/src/main/java/io/f1/backend/domain/admin/app/handler/AdminLoginFailureHandler.java
  backend/src/main/java/io/f1/backend/domain/admin/app/handler/AdminLoginSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/auth/api/AuthController.java
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/GameResultResponse.java
  backend/src/main/java/io/f1/backend/domain/game/event/GameCorrectAnswerEvent.java
  backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java
  backend/src/main/java/io/f1/backend/domain/game/sse/store/SseEmitterRepository.java
  backend/src/main/java/io/f1/backend/domain/game/store/UserRoomRepository.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/DisconnectTaskManager.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/service/SessionService.java
  backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
  backend/src/main/java/io/f1/backend/domain/user/api/UserController.java
  backend/src/main/java/io/f1/backend/domain/user/app/UserService.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/CustomAuthenticationEntryPoint.java
  backend/src/main/java/io/f1/backend/domain/user/app/handler/UserAndAdminLogoutSuccessHandler.java
  backend/src/main/java/io/f1/backend/domain/user/dto/UserPrincipal.java
  backend/src/main/java/io/f1/backend/global/exception/errorcode/CommonErrorCode.java
  backend/src/main/java/io/f1/backend/global/lock/CustomSpringELParser.java
  backend/src/main/java/io/f1/backend/global/lock/DistributedLock.java
  backend/src/main/java/io/f1/backend/global/lock/DistributedLockAspect.java
  backend/src/main/java/io/f1/backend/global/security/util/SecurityUtils.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/redisson.yaml
  backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/websocket/SessionServiceTests.java
  backend/src/test/java/io/f1/backend/domain/stat/RedisStatBrowserTest.java
  backend/src/test/java/io/f1/backend/global/config/RedisTestContainerConfig.java
  backend/src/test/java/io/f1/backend/global/lock/DistributedLockAspectTests.java
  backend/src/test/java/io/f1/backend/global/lock/DistributedLockIntegrationTest.java
  backend/src/test/resources/application.yml
Labels: bump:patch

#170 [feat] 채팅 정답 처리 동시성 제어
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/test/java/io/f1/backend/domain/game/app/ChatServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/app/GameFlowTests.java
Labels: enhancement

#172 [feat] 하트비트 구현
  backend/src/main/java/io/f1/backend/BackendApplication.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/HeartbeatResponse.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/HeartbeatMonitor.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/HeartbeatController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java
  backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java
Labels: enhancement

#174 [fix] 마이페이지 DTO 값 순서 변경
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRedisRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepositoryAdapter.java
Labels: bug

#175 [release] v0.0.14 RELEASE
  backend/build.gradle
  backend/src/main/java/io/f1/backend/BackendApplication.java
  backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java
  backend/src/main/java/io/f1/backend/domain/game/app/GameService.java
  backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java
  backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java
  backend/src/main/java/io/f1/backend/domain/game/dto/response/HeartbeatResponse.java
  backend/src/main/java/io/f1/backend/domain/game/model/Room.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/HeartbeatMonitor.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/controller/HeartbeatController.java
  backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRedisRepository.java
  backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepositoryAdapter.java
  backend/src/main/java/io/f1/backend/global/config/RedisConfig.java
  backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/test/java/io/f1/backend/domain/game/app/ChatServiceTests.java
  backend/src/test/java/io/f1/backend/domain/game/app/GameFlowTests.java
  backend/src/test/resources/application.yml
Labels: bump:patch
